name: Update Version

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bump version
        run: |
          git config --global user.name 'dusanpetkovicdsaga'
          git config --global user.email 'dukisaga@yahoo.com'
          git checkout -b version-bump-$(date +%s)
          npm version patch -m "Bump version to %s [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'Bump version to $(jq -r .version package.json) [skip ci]'
          branch: version-bump-$(date +%s)
          title: 'Bump version to $(jq -r .version package.json)'
          body: 'This PR bumps the version to $(jq -r .version package.json).'

      - name: Merge Pull Request
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:version-bump-$(date +%s)`
            });

            if (pullRequests.length > 0) {
              const pullRequest = pullRequests[0];
              if (pullRequest.user.login === 'dusanpetkovicdsaga') {
                await github.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pullRequest.number,
                  merge_method: 'merge'
                });
              }
            }
